apiVersion: metaspore/v1
kind: OfflineCrontabScheduler
metadata:
  name: offline_crontab_scheduler
spec:
  cron_expr: "0 0 * * *"
  dag:
    sync_data: [ "join_data_1", "join_data_2" ]
    join_data_1: [ "train_model_1" ]
    join_data_2: [ "train_model_2" ]

